# Generated by Django 6.0.5 on 2026-06-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_action', models.CharField(choices=[('quiz', 'Quiz personnalisé'), ('meeting', 'Réunion parents-professeurs'), ('followup', 'Séances de suivi'), ('counseling', 'Orientation psychologue scolaire')], max_length=20)),
                ('description', models.TextField()),
                ('explanation_primary_factor', models.TextField()),
                ('explanation_secondary_factor', models.TextField(blank=True)),
                ('explanation_basis', models.TextField()),
                ('confidence', models.FloatField()),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_risk_threshold', models.IntegerField(default=70, help_text='Score à partir duquel le risque est élevé (0-100)')),
                ('medium_risk_threshold', models.IntegerField(default=40, help_text='Score à partir duquel le risque est moyen (0-100)')),
                ('alert_threshold', models.IntegerField(default=50, help_text='Score à partir duquel une alerte est générée (0-100)')),
                ('absence_weight', models.IntegerField(default=40, help_text='Pondération absences (%)')),
                ('grade_weight', models.IntegerField(default=40, help_text='Pondération notes (%)')),
                ('behavior_weight', models.IntegerField(default=20, help_text='Pondération comportement (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration des seuils',
                'verbose_name_plural': 'Configurations des seuils',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('ignored', 'Ignoré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='early_warning.aisuggestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('quiz', 'Quiz personnalisé'), ('meeting', 'Réunion parents-professeurs'), ('followup', 'Séances de suivi'), ('counseling', 'Orientation psychologue scolaire'), ('custom', 'Action personnalisée')], max_length=20)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='early_warning.aisuggestion')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='early_warning.alert')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('class_name', models.CharField(max_length=100)),
                ('absences', models.IntegerField()),
                ('avg_grade', models.FloatField()),
                ('behavior_score', models.IntegerField(help_text='Score comportement (0-10)')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Elevé')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-risk_score'],
                'indexes': [models.Index(fields=['student_id'], name='early_warni_student_f83631_idx'), models.Index(fields=['class_name'], name='early_warni_class_n_5ed2cd_idx'), models.Index(fields=['risk_level'], name='early_warni_risk_le_8ed8f1_idx')],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='risk_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='early_warning.riskscore'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='early_warni_status_81e0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='early_warni_created_62b4db_idx'),
        ),
    ]
