# Generated by Django 6.0.5 on 2026-06-06 22:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', '🎓 Étudiant'), ('parent', '👨\u200d👩\u200d👧 Parent'), ('teacher', '📚 Professeur'), ('counselor', '🧠 Conseiller scolaire'), ('admin', '👑 Administrateur')], default='student', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('psychologist', 'Psychologue scolaire'), ('orientation', "Conseiller d'orientation"), ('social', 'Assistant social'), ('educator', 'Éducateur spécialisé')], max_length=20, verbose_name='Spécialité')),
                ('license_number', models.CharField(max_length=50, verbose_name='Numéro de licence')),
                ('available_for_chat', models.BooleanField(default=True, verbose_name='Disponible pour chat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conseiller',
                'verbose_name_plural': 'Conseillers',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('primary', '🏫 Primaire (6-11 ans)'), ('middle', '📚 Collège (12-14 ans)'), ('high', '🎓 Lycée (15-17 ans)'), ('university', '🏛️ Université (18-25 ans)')], max_length=20, verbose_name='Niveau scolaire')),
                ('high_school_speciality', models.CharField(blank=True, choices=[('math', 'Mathématiques'), ('sciences', 'Sciences Expérimentales'), ('tech', 'Sciences Techniques'), ('economics', 'Économie & Gestion'), ('letters', 'Lettres'), ('sports', 'Sport')], max_length=20, null=True)),
                ('high_school_year', models.IntegerField(blank=True, help_text='1,2,3,4', null=True)),
                ('university_major', models.CharField(blank=True, choices=[('cs', '💻 Informatique / Génie Logiciel'), ('med', '🩺 Médecine / Pharmacie'), ('eng', '🔧 Ingénierie'), ('business', '📈 Commerce / Finance'), ('law', '⚖️ Droit'), ('economics', '📊 Sciences Économiques'), ('letters', '📖 Lettres / Langues'), ('arts', '🎨 Arts / Design'), ('science', '🔬 Sciences Fondamentales'), ('agri', '🌾 Agriculture')], max_length=30, null=True)),
                ('university_year', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Établissement')),
                ('anonymous_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID anonyme')),
                ('total_study_hours', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('total_quizzes_completed', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('total_quiz_points', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil étudiant',
                'verbose_name_plural': 'Profils étudiants',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.studentprofile', verbose_name='Enfants')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='linked_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_parents', to='accounts.studentprofile', verbose_name='Étudiant lié'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Mathématiques'), ('physics', 'Physique-Chimie'), ('french', 'Français'), ('arabic', 'Arabe'), ('english', 'Anglais'), ('history', 'Histoire-Géographie'), ('science', 'Sciences'), ('informatics', 'Informatique'), ('philosophy', 'Philosophie'), ('sports', 'Sport')], max_length=50, verbose_name='Matière enseignée')),
                ('school', models.CharField(max_length=200, verbose_name='Établissement')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
            },
        ),
    ]
