# Generated by Django 6.0.5 on 2026-06-06 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import_csv', 'Import CSV'), ('import_csv_error', 'Import CSV - Erreur'), ('import_csv_malformed', 'Import CSV - Malformé'), ('update_threshold_config', 'Modification des seuils'), ('create_intervention', 'Création intervention'), ('update_intervention_status', 'MAJ statut intervention'), ('export_csv', 'Export CSV'), ('export_pdf', 'Export PDF'), ('access_alert_detail', 'Accès détail alerte'), ('access_threshold_config', 'Accès configuration seuils'), ('graphql_query', 'Requête GraphQL'), ('graphql_mutation', 'Mutation GraphQL'), ('graphql_generate_suggestion', 'Génération suggestion IA'), ('graphql_update_alert', 'MAJ alerte via GraphQL'), ('graphql_create_intervention', 'Création intervention via GraphQL'), ('graphql_bulk_update_alerts', 'MAJ groupée alertes'), ('unauthorized_access', 'Accès non autorisé'), ('login_attempt', 'Tentative de connexion'), ('logout', 'Déconnexion'), ('ai_intervention_suggestion', 'Suggestion IA'), ('mcp_fallback', 'Fallback MCP'), ('health_check', 'Health check')], db_index=True, max_length=50)),
                ('result', models.CharField(choices=[('success', '✅ Succès'), ('error', '❌ Erreur'), ('blocked', '🚫 Bloqué'), ('fallback', '⚠️ Fallback'), ('warning', '⚠️ Attention')], db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('case_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['action', 'result'], name='audit_audit_action_4c922e_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx')],
            },
        ),
    ]
