# Generated by Django 6.0.5 on 2026-06-01 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_identity', 'Tentative de voir identité réelle'), ('override_category', 'Override catégorie IA'), ('access_denied', 'Accès refusé'), ('websocket_disconnect', 'Déconnexion WebSocket'), ('security_violation', 'Violation de sécurité')], max_length=50)),
                ('resource', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(max_length=50)),
                ('ai_category', models.CharField(choices=[('stress', '😰 Stress / Examens'), ('family', '👨\u200d👩\u200d👧 Problèmes familiaux'), ('school', '📚 Problèmes scolaires'), ('anxiety', '🌪️ Anxiété / Angoisses'), ('other', '💬 Autre')], default='other', max_length=20)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_trace_id', models.CharField(blank=True, max_length=100)),
                ('overridden_category', models.CharField(blank=True, choices=[('stress', '😰 Stress / Examens'), ('family', '👨\u200d👩\u200d👧 Problèmes familiaux'), ('school', '📚 Problèmes scolaires'), ('anxiety', '🌪️ Anxiété / Angoisses'), ('other', '💬 Autre')], max_length=20, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('closed', 'Clôturée')], default='pending', max_length=20)),
                ('urgency_level', models.CharField(choices=[('low', '🟢 Faible'), ('medium', '🟠 Modéré'), ('high', '🔴 Urgent')], default='low', max_length=10)),
                ('student_age_group', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_summary', models.TextField(blank=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('counselor_channel', models.CharField(blank=True, max_length=255)),
                ('student_channel', models.CharField(blank=True, max_length=255)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('health_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='health.healthrequest')),
            ],
        ),
        migrations.CreateModel(
            name='HealthTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Création de la demande'), ('ia_categorized', 'Catégorisation IA'), ('ia_override', 'Override par conseiller'), ('assigned', 'Prise en charge'), ('message_sent', 'Message envoyé'), ('closed', 'Clôture')], max_length=20)),
                ('actor', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='health.healthrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('sender_role', models.CharField(choices=[('student', 'Étudiant'), ('counselor', 'Conseiller'), ('system', 'Système')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='health.healthrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
